apiVersion: v1
items:
- apiVersion: v1
  data:
    password: ""
    username: c2E=
  kind: Secret
  metadata:
    creationTimestamp: "2022-09-27T10:29:28Z"
    name: db-password
    namespace: default
    resourceVersion: "1648284"
    uid: b6007ee1-b45f-4350-8ccb-b8377826bcc9
  type: Opaque
- apiVersion: v1
  data:
    ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE1TWpJeApNREU1TVRsYUZ3MDBNakE1TWpJeE1ERTVNVGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEaEdGMVRuT0hHQW5Fall4OEw0clBXbklmSGhIUVZPSWdnVVNkWVVOekdza0lIajVSWQpNeEozZVRXdi9UTm9KanQ4S09kSzZrdnNDVzRpSFp2bnlUOURkbUNSSlZCd3NmUVhNZEpPVEtveXhPZVBHUkliCjlnaHpkeldCMDkyWXVoM2MzdmNhUzA3VE5mWW1kenMxNXUySG5YZ0JLTm9TZkd1U2tmb2FrdjNtaTNaczhac0wKWTFEVjhBU1ZXeEUvcEtvemUzYWU3aXJlSXRMVzB1YTlEanEyb09GM2FiS0RheXkyTURVTGs4RFovdzd4MmZNUgozUGh0SkJQS0FLd3RQcGN1T2s2MXZwaDNyYkRTRW9uZUgwZ0duV3hlUXhJQVBzVHdUajVSOVI2NDNRb0JHSXBlCjJvRE5Ld0VTQUdHTVpPQ1JXOHJDWWFhUmc0ZW9YVC80TjdmZEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFLRU1XZjdmWG9LalVnQVljZAp2YzUwSk56R0pEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFPV1VLRWlJNVVXN05QaHliWjhGZWZ6cHhNM1V6CllCMmFOZWhrTHppWXkwelArL1Q0Rk1PYmY3Njg1cUxnTHpvN0VudVI1L2Rlcmp0SHd2QnZtZGJQa0JmTlpVSlUKOVd1L2RkeVk0b0I0QnptQ2hDc2J6djNVRStOcGxrVFZ2U0hvMGdGSHZlTlNXNGtIZ3IycVRvVDZqT0V3TE4rdAp5akRLSVM5N2ZBbTlZM3B3RGZNS0gxQlpoZ1hRV2lmV1BwR0xRK2d1YjNCOTRyRFpVeTFPYnk4NHQwWE45OXY1Ck9xd0M2SVRTTHdRMTlLRkJCQWtBRURoRVVkaWh6QUhHcFRzMUUwc1hYczA1ZjkvaWVIRko1TGQ0bWZMVDZJRWkKcXJrQUpwdVZQMXFxWW1HQzZNeEdCRXZoK1lvcjNPMDBCM1p5WTcwZklNZDE1ZXl2cXZSU1BNNTBWQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    namespace: ZGVmYXVsdA==
    token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltMUJiVFpMTVRaYU56SjNZelJwWlRkclJESTFaVkZFUTFVemNHMXJWbWt5YnpKdFZ6RXdVbXRtWnpBaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbVJsWm1GMWJIUXRkRzlyWlc0dGJXZHllSG9pTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pWkdWbVlYVnNkQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJbVkzTjJNeE5EQmhMVGd5Tm1JdE5EYzFPUzA0TXpCbExXVTJaR1l3TURjeU1ERXdaaUlzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwa1pXWmhkV3gwT21SbFptRjFiSFFpZlEuTTAwWkYtV2xhYk5kRm9rSFh4dzladDJ3aU9WTHVsT0VJRjdYeTFuSGNHY1hoQU55NmxEbmItOFRhdWxWeC0zeXR1djlQelZCUjN4aTM5MGN1bXpuUFkyb19ZU2VFZ0FVai1HaWdPSXVZWlMxcTdCUUlZanFCRVpwRVE4bk83UmpSRWpXWXJvRFF5bVdpczlaZjhMcDZydm9VMU1mMGdYZVpEeEFwTkIzZ2RpQWR2MGstWE81Wllub2hadXdVd21NSG1Ecm5SLW1DOHV5amE1MVVROUxRS2lMb1poVjEya0dINFd0UVVER2Z3Qll6a1EzTmhSNG5wN0RIWHVaTWlYMEp6c0lnZkhKX08wNmpGejBWNkwwWVZKbmNUamotZjNfbDEwZC1rVzBVMlVITnFCRHZOekZObGJZV3hhSXkzaVdRSXJWZXAtMzFwMDhlc19Bd3dlTEFR
  kind: Secret
  metadata:
    annotations:
      kubernetes.io/service-account.name: default
      kubernetes.io/service-account.uid: f77c140a-826b-4759-830e-e6df0072010f
    creationTimestamp: "2022-09-22T10:20:15Z"
    name: default-token-mgrxz
    namespace: default
    resourceVersion: "320"
    uid: 31849c92-462a-4125-a99b-92bda6855862
  type: kubernetes.io/service-account-token
kind: List
metadata:
  resourceVersion: ""
